### ISSUE TITLE
Feature Request: measure repeat interval from @done time

### ISSUE THREAD

**Issue by apkawel** [dannynelson/taskpaper-repeat#1]
It would be nice if the script added an option to repeat the task with start/due dates measured from the completion time instead of the original start/due times.

Ex: the task
`- test @due(2017-10-09) @repeat(+2d)`
when completed would become
`- test @due(2017-10-09) @repeat(+2d) @done(2017-10-08)`
and would repeat as
`- test @due(2017-10-10) @repeat(+2d)`
instead of
`- test @due(2017-10-11) @repeat(+2d)`

I hope that makes sense. Maybe this could be accomplished with different `@repeat` tags, such as `@repeatstart` and `@repeatdone`?

With a few tweaks, this script could put TaskPaper at or above the OmniFocus level.

Thanks for your work on this—great script!

**Comment by dannynelson** [comment]
@apkawel that's a great idea. In [v2.0.0](https://github.com/dannynelson/taskpaper-repeat/releases), you can add the the `@repeat-from-done` tag to repeat from completion date instead of `@start`/`@due` date.
```
- repeat 1 week after completion @due(2018-11-11) @repeat(+1 week) @repeat-from-done
- repeat the Monday after completion @start(2018-11-11) @repeat(Monday) @repeat-from-done
```
Let me know what you think!
