### ISSUE TITLE
Appears not to deal with notes

### ISSUE THREAD

**Issue by jgclark** [dannynelson/taskpaper-repeat#2]
I'm testing this out before adopting it.  In this small test case:

`- test-note @due(today) @repeat(+1 week) @other @tags @here`
`This is the note to go with it.`

Unfortunately it doesn't work as expected as the new task doesn't have the notes. Minimally, the updated copy of the repeated task could be placed under the completed one, and the notes would move over to it. Though ideally it should be fully duplicated.

**Comment by stevelw** [comment]
@jgclark I know this was a while ago, but in case you're still stuck the error is in your example not the script. You example is a task item followed by a note item. To make the note item part of the task item you need to tab it over.
```
- test-note @due(today) @repeat(+1 week) @other @tags @here
	This is the note to go with it.
```

**Comment by jgclark** [comment]
Thanks, @stevelw, that should help others as well.
