### ISSUE TITLE
Error in date arithmetic?

### ISSUE THREAD

**Issue by jgclark** [dannynelson/taskpaper-repeat#3]
I think there's a bug that occurs occasionally:

With test task:
`- testzzz @due(2019-02-01) @start(2018-12-01) @repeat(+2 months) @done(2019-01-11)`
it produces this repeat:
`- testzzz @due(2019-04-04 01:00) @start(2019-02-01) @repeat(+2 months)`

I was expecting
`- testzzz @due(2019-04-01 01:00) @start(2019-02-01) @repeat(+2 months)`

**Comment by stevelw** [comment]
Doesn't look like a bug to me — with both a start and due date it is the start date that is set to +2 months. The due date is then the same number of days after the start dates.

**Comment by dannynelson** [comment]
Thanks @stevelw. Yes, this is working as intended.
